### PR TITLE
Update graph_object_cn.md

### PR DESCRIPTION
**Pull request by HuangLED**
markdown格式错误，缺少一个空行导致标题无法正常显示。

此外描述中缺少个单位，我猜测是GB.

### CODE REVIEW

**Comment by sighingnow** [comment]
Looks good to me.

Merged. Thank you for fixing that @HuangLED.

**Comment by HuangLED** [comment]
> Looks good to me.
> 
> Thank you for fixing that @HuangLED.

My pleasure. 

Ping for merge.  @jackonan

**Comment by HuangLED** [comment]
@sighingnow  Ping for merge.

**Comment by HuangLED** [comment]
@Seventeen17

**Pull request closed without merging**
